/* confdefs.h */
#define PACKAGE_NAME "GenAlgPLSConfig"
#define PACKAGE_TARNAME "genalgplsconfig"
#define PACKAGE_VERSION "version-1.0"
#define PACKAGE_STRING "GenAlgPLSConfig version-1.0"
#define PACKAGE_BUGREPORT ""
#define PACKAGE_URL ""
#define STDC_HEADERS 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_MEMORY_H 1
#define HAVE_STRINGS_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_UNISTD_H 1
#define HAVE_UINT64_MAX 1
#define HAVE_UINT64_MAX 1
#define HAVE_UINT32_MAX 1
#define HAVE_UINT32_MAX 1
#define HAVE_UINT8_16_MAX 1
#define HAVE_UINT8_16_MAX 1
